<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE friends [
    <!ELEMENT friends (self, friend*)>
    <!ELEMENT self (id, name, age, major)>
    <!ELEMENT friend (id, name, age, major)>
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT age (#PCDATA)>
    <!ELEMENT major (#PCDATA)>
]>
<friends>
    <self>
        <id>18</id>
        <name>Asit Kumar</name>
        <age>20</age>
        <major>Computer Science</major>
    </self>
    <friend>
        <id>8</id>
        <name>Akash Mahato</name>
        <age>21</age>
        <major>Mathematics</major>
    </friend>
    <friend>
        <id>61</id>
        <name>Sonu Prajapati</name>
        <age>21</age>
        <major>Physics</major>
    </friend>
    <friend>
        <id>23</id>
        <name>Dheeraj Kumar</name>
        <age>21</age>
        <major>Chemistry</major>
    </friend>

</friends>